name: Build & Deploy Portfolio

on:
  push:
    branches: ["main"]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Create dist folder
        run: |
          mkdir dist

      - name: Generate HTML
        run: node build/generate.js

      - name: Copy static files
        run: |
          cp -r css dist/
          cp -r javascript dist/
          cp favicon.ico dist/
          cp index.html dist/

      - name: Check dist folder
        run: |
          ls -R dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v5
